title: Just the Docs test
description: Test tworzenia stron statycznych
theme: just-the-docs

url: https://makwojwwa.github.io/JustTheDocsTest

aux_links:
  Template Repository: https://github.com/makwojwwa/JustTheDocsTest
